#! /usr/bin/env python
import re
import sqlite3;

db = sqlite3.connect('parts.db')

c = db.cursor()

# Assuming the database doesn't exist.
c.execute('create table parts(part text, value text, device text, package text, library text, sheet integer);')

ff = open("pp", "r")
list = ""
lines = ff.readlines()

for line in lines[9:]:
    part = line[0:9].strip()
    value = line[9:28].strip()
    device = line[28:47].strip()
    package = line[47:60].strip()
    lib = line[60:73].strip()
    sheet = line[73:-1].strip()
    
    c.execute('insert into parts values(?,?,?,?,?,?);', (part, value, device, package, lib, sheet))

# Must do this before exiting or the changes will not be written.
db.commit()
