#!/usr/bin/python

import sys

if len(sys.argv) != 2:
    print 'Converts a TI SmartRF .prs (packet sniffer) export file to a C array.'
    print ''
    print 'Usage: ' + sys.argv[0] + ' <input.prs>'
    sys.exit(0)

input = file(sys.argv[1], 'rt')

print 'const uint8_t cc1101_regs[] PROGMEM ='
print '{'
for line in input:
    fields = line.split('|')
    name = fields[0];
    addr = fields[1].lower();
    value = fields[2].lower();
    desc = fields[3].strip();
    print '    ' + addr + ', ' + value + ',    // ' + name + ' - ' + desc
print '};'
print ''
