(part "TMUX1204DGSR"
    (packageRef "SOP50P490X110-10N")
    (interface
        (port "1" (symbPinId 1) (portName "A0") (portType INPUT))
        (port "2" (symbPinId 2) (portName "S1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "GND") (portType GROUND))
        (port "4" (symbPinId 4) (portName "S3") (portType INOUT))
        (port "5" (symbPinId 5) (portName "EN") (portType INPUT))
        (port "6" (symbPinId 6) (portName "VDD") (portType POWER))
        (port "7" (symbPinId 7) (portName "S4") (portType INOUT))
        (port "8" (symbPinId 8) (portName "D") (portType INOUT))
        (port "9" (symbPinId 9) (portName "S2") (portType INOUT))
        (port "10" (symbPinId 10) (portName "A1") (portType INPUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "595-TMUX1204DGSR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/TMUX1204DGSR?qs=EBDBlbfErPw42Q0DdvAwUg%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "TMUX1204DGSR")
    (property "Description" "5-V 4:1 general-purpose analog multiplexer")
    (property "Datasheet_Link" "http://www.ti.com/lit/gpn/TMUX1204")
    (property "symbolName1" "TMUX1204DGSR")
)
