(part "RM106772BCB"
    (packageRef "RM106772BCB")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
        (port "5" (symbPinId 5) (portName "5") (portType INOUT))
        (port "6" (symbPinId 6) (portName "6") (portType INOUT))
        (port "7" (symbPinId 7) (portName "7") (portType INOUT))
        (port "C1" (symbPinId 8) (portName "C1") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "162")
    (property "Mouser_Part_Number" "611-RM106772BCB")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/CK/RM106772BCB?qs=367PjNmvCmlxoAu0%2F1HoEg%3D%3D")
    (property "Manufacturer_Name" "LITTELFUSE")
    (property "Manufacturer_Part_Number" "RM106772BCB")
    (property "Description" "Rotary Switches .2A 48VDC 6pos Stop 7.7mm Act 270gf")
    (property "Datasheet_Link" "https://www.digikey.ph/en/products/detail/c-k/RM106772BCB/6052015")
    (property "symbolName1" "RM106772BCB")
)
