(part "OS102011MS2QN1"
    (packageRef "OS102011MA1QN1")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "162")
    (property "Mouser_Part_Number" "611-OS102011MS2QN1")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/CK/OS102011MS2QN1?qs=WtljUlYws5RvQ1hEv876nQ%3D%3D")
    (property "Manufacturer_Name" "LITTELFUSE")
    (property "Manufacturer_Part_Number" "OS102011MS2QN1")
    (property "Description" "Switch Slide Miniature SPDT 0.1A 12VDC Through Hole Slide Switch SPDT On-On 0.1 A@ 12 V dc Slide")
    (property "Datasheet_Link" "https://www.ckswitches.com/media/1428/os.pdf")
    (property "symbolName1" "OS102011MS2QN1")
)
